# Based on https://pnpm.io/docker
FROM node:24-trixie-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
RUN corepack enable
WORKDIR /app
COPY . .

# Build app
FROM base AS build
ENV CI=true
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm build

# Combine and run
FROM nginx:alpine AS run
WORKDIR /app
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./container/custom-nginx-default.conf /etc/nginx/conf.d/default.conf
ENV NODE_ENV=production
# CMD ["node", "dist/index.js"] # Not needed since nginx runs