# Generated by Django 6.0.7 on 2026-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_comment='Webpage title')),
                ('authors', models.JSONField(db_comment='JSON-stored list of authors', default=list)),
                ('source', models.TextField(db_comment='Webpage source URL')),
                ('last_updated_timestamp', models.DateTimeField(db_comment='The last known timestamp at which this novel was modified')),
                ('last_fetch_timestamp', models.DateTimeField(db_comment='The last timestamp at which this novel was fetched/rescanned')),
            ],
        ),
        migrations.CreateModel(
            name='WebpageCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_comment='Collection title')),
                ('authors', models.JSONField(db_comment='JSON-stored list of authors', default=list)),
                ('status', models.TextField(choices=[('ACTIVE', '連載中'), ('COMPLETED', '完結')], db_comment='Novel status (i.e. actively being written, completed, etc.)')),
                ('last_updated_timestamp', models.DateTimeField(db_comment='The last known timestamp at which this novel was modified')),
                ('last_fetch_timestamp', models.DateTimeField(db_comment='The last timestamp at which this novel was fetched/rescanned')),
                ('frozen', models.BooleanField(db_comment='Whether fetching for this novel has been disabled or not', default=False)),
            ],
        ),
    ]
