# Generated by Django 6.0.7 on 2026-08-01 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.BigIntegerField(db_comment='Chapter number', unique=True)),
                ('chapter_title', models.TextField(blank=True, db_comment='Chapter title')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_comment='Novel title')),
                ('author', models.TextField(db_comment='Author name')),
                ('source', models.TextField(db_comment='Source URL', unique=True)),
                ('status', models.TextField(choices=[('ACTIVE', '連載中'), ('COMPLETED', '完結')], db_comment='Novel status (i.e. actively being written, completed, etc.)')),
                ('last_updated_timestamp', models.DateTimeField(db_comment='The last known timestamp at which this novel was modified')),
                ('last_fetch_timestamp', models.DateTimeField(db_comment='The last timestamp at which this novel was fetched/rescanned')),
                ('frozen', models.BooleanField(db_comment='Whether fetching for this novel has been disabled or not', default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_src', models.TextField(db_comment='The original image path')),
                ('image_file', models.ImageField(upload_to='embedded_images')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.BigIntegerField(db_comment='Episode nnumber', unique=True)),
                ('episode_title', models.TextField(db_comment='Episode title')),
                ('last_known_update_timestamp', models.DateTimeField(db_comment='The last known timestamp at which this episode was updated (used for tracking revisions)', null=True)),
                ('contents', models.TextField(db_comment='The HTML content for the episode contents')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
    ]
