# Generated by Django 6.0.7 on 2026-08-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_number',
            field=models.BigIntegerField(db_comment='Chapter number'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_number',
            field=models.BigIntegerField(db_comment='Episode number'),
        ),
    ]
