# Generated by Django 6.0.7 on 2026-08-02 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_alter_chapter_chapter_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpubFile',
            fields=[
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='novels.novel')),
                ('file', models.FileField(upload_to='epub_out')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='source_src',
            field=models.TextField(db_comment='The original image path', unique=True),
        ),
    ]
