# Generated by Django 6.0.7 on 2026-08-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_epubfile_alter_uploadedimage_source_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epubfile',
            name='novel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='novels.novel'),
        ),
    ]
