# Generated by Django 6.0.7 on 2026-08-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_alter_epubfile_novel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='last_updated_timestamp',
            field=models.DateTimeField(db_comment='The last known timestamp at which this novel was modified by the author'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.TextField(choices=[('ACTIVE', '連載中'), ('COMPLETED', '完結'), ('ABANDONED', '未完')], db_comment='Novel status (i.e. actively being written, completed, etc.)'),
        ),
    ]
