# Generated by Django 6.0.7 on 2026-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_alter_novel_last_updated_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='postprocess_indent_separators',
            field=models.BooleanField(db_comment='Whether or not to indent lines which appear to be separators (lines comprised of just symbols)', default=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='postprocess_reduce_blank_lines',
            field=models.BooleanField(db_comment='Whether or not to reduce the amount of blank newlines', default=True),
        ),
        migrations.AddField(
            model_name='novel',
            name='postprocess_replace_hrs',
            field=models.BooleanField(db_comment='Whether or not to replace <hr/> tags with less intrusive alternatives', default=True),
        ),
    ]
