# Generated by Django 6.0.7 on 2026-08-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0006_novel_postprocess_indent_separators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='postprocess_auto_indent',
            field=models.BooleanField(db_comment="Whether or not to indent all lines which start with text (and aren't already indented)", default=True),
        ),
    ]
