# Generated by Django 6.0.7 on 2026-08-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0007_novel_postprocess_auto_indent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='status',
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.JSONField(db_comment='List of ovel tags as strings (if any; empty list if none or not supported)', default=list),
        ),
    ]
