// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.ChapterSerializer
// Digest: a5a2e9cdd033f826eb650b7a2ec3c143dc5d2f01bce342867aca9ee3fd7b8451
// Last modified on: 2026-08-04T05:48:02.791933

export interface Chapter {
  id: any;
  chapterNumber: any;
  chapterTitle: string;
  novel: any;
}