// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.EpisodeSerializerWithoutContents
// Digest: 7377ca3c3566c2591d638adb21efb8896738cfafb9cf2f8cecbbe08d2dc295e9
// Last modified on: 2026-08-04T05:48:02.792393

export interface EpisodeWithoutContents {
  id: any;
  chapter: any;
  episodeNumber: any;
  episodeTitle: string;
  lastKnownUpdateTimestamp: Date | null;
}