// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.EpisodeSerializer
// Digest: f9ab785f084ad53e5b95cc5febc834b8e5525fcbe72c700c9fde578954e6bd21
// Last modified on: 2026-08-04T05:48:02.792192

export interface Episode {
  id: any;
  episodeNumber: any;
  episodeTitle: string;
  lastKnownUpdateTimestamp: Date | null;
  contents: string;
  chapter: any;
}