// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.EpubFileSerializer
// Digest: dce8db8107177f41f6c588526ad1a9cb44432e3c2a858bf8951a244c5a96e543
// Last modified on: 2026-08-04T05:26:32.147897

export interface EpubFile {
  novel: any;
  file: any;
}