// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.NovelSerializer
// Digest: 633004cd6f29a14f71510e3182f39ce2eeed58b9bfc5d3a8fecf7082205f22f7
// Last modified on: 2026-08-17T05:44:37.904179

export interface Novel {
  id: any;
  title: string;
  author: string;
  source: string;
  tags: any;
  lastUpdatedTimestamp: Date;
  lastFetchTimestamp: Date;
  frozen: boolean;
  postprocessReduceBlankLines: boolean;
  postprocessIndentSeparators: boolean;
  postprocessReplaceHrs: boolean;
  postprocessAutoIndent: boolean;
}