// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.NovelSerializer
// Digest: 41c959f68c7442e723474448b0a962c034957e43b712d60fc789c6bd295fb98b
// Last modified on: 2026-08-04T05:52:04.479204

export interface Novel {
  id: any;
  title: string;
  author: string;
  source: string;
  status: '連載中' | '完結' | '未完';
  lastUpdatedTimestamp: Date;
  lastFetchTimestamp: Date;
  frozen: boolean;
}