// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.NovelSerializer
// Digest: 2fc0915986218663b1c00fbdcc27aa6ec841b0daa6e3b976809900dc3425f4ac
// Last modified on: 2026-08-17T03:43:14.560281

export interface Novel {
  id: any;
  title: string;
  author: string;
  source: string;
  status: '連載中' | '完結' | '未完';
  lastUpdatedTimestamp: Date;
  lastFetchTimestamp: Date;
  frozen: boolean;
  postprocessReduceBlankLines: boolean;
  postprocessIndentSeparators: boolean;
  postprocessReplaceHrs: boolean;
  postprocessAutoIndent: boolean;
}