// This file is generated by django-rest-typescript-generator@0.0.2.
// You are strongly advised not to manually change this file for backend consistency.
// Source Type: novels.serializers.UploadedImageSerializer
// Digest: cba5ead296f862af072412d017cb5167bbbc857a6283f7691f8a0db2aac0bbdd
// Last modified on: 2026-08-04T05:48:02.792578

export interface UploadedImage {
  id: any;
  sourceSrc: string;
  imageFile: any;
}